spring:
  datasource:
    url: jdbc:h2:./devdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: update 
      
  data:
    web:
      pageable:
        page-parameter: currentPage
        size-parameter: pageSize